### PR TITLE
 Yak shaving, now we have bower.json and package.json

### PR DESCRIPTION
**Pull request by jorgehjr84**
### Feature/mobile/tabs
- [ ] Setting up the skeleton in HTML
- [ ] Unrelated to the tabs feature make sure you set your body and "container" elements before you progress.
- [ ] Create the NAV Element in HTML with a <nav> tag
- [ ] Below that <nav> create the UL element
- [ ] We need 2 separate Li's now.
- [ ] Styling for what we created in HTML for the tabs
- [ ] First we should probably set a width for those NAV and UL elements
- [ ] Now that we have that setup we should probably set the display to 'inline-block' not sure if we should do this in the nav or ul element
- [ ] What position should we have for the NAV? I believe it should be 'relative' to its parent container
- [ ] Once we have 'position:relative'  we can set the top to maybe 2em???
- [ ] Next we can put text in between the li tags in the HTML form. For example  About and Repositories
- [ ]  Call up the li element in CSS and set the color to blue
- [ ] Set the border to lightgrey for the li's
- [ ] Set the li width to full page but set the height to whatever looks good. Maybe 1-2ems?
- [ ] Do the li properties need to be set to float?
### Feature/mobile/tabs
- [ ] Setting up the skeleton in HTML
- [ ] Create a new div to contain the entire popular repos section
- [ ] Inside that div create the ul and 6 lis
- [ ] within the li's maybe use anchor tags? 
- [ ] Within each li create two sub divs . One octocat/spoon-knife section and one for number of "fav's"
- [ ] Styling for what we created in HTML for the tabs
- [ ] Set the width for the NAV and UL sections
- [ ] First maybe set the UL to display:block, so that the LI's will live on top of each other
- [ ] Grey borders for ul and li's 
- [ ] Set the width for the repo name div and the followers div along with the height property
- [ ] Set the icon for the repo div to ::before
  *[ ] Set the star icon ::after the followers div
- [ ] Set the 'color' to cornflower blue in the repo div container. Along with a text-align center
  *[ ] Set margin for repo div and followers div? Or do we just float the repo div left and the follower div right?
### Feature/mobile/details
- [ ] Setup H5BP `index.html` 
- [ ] Wire `main.css` 
- [ ] Create `body` element
- [ ] Create `container` element
- [ ] Within `container`, create 3 sections (boxes!) - section, button, section?

**INFO Section**
- [ ] Features an image, title, and list items
- [ ] Image element - Left side of section
- [ ] Image element - Does not fill the entire height of the section
- [ ] Title `<h3>` element - Right of image, above the list items
- [ ] Title - Text is larger than list items
- [ ] List Items - Featured below title, smaller font, color darkgrey?
- [ ] List Items - Features Icons to the left of item text, also darkgrey?
- [ ] Title & List Items - Together as `display: block` ?
- [ ] INFO Section has a bottom border - lightgrey

**BUTTON Section**
- [ ] Button element - Full width of page
- [ ] Button element - Styled with background color `green`
- [ ] Button element - Features Icon and Text - colored white, aligned center of button

**STATS Section**
- [ ] Features 1 row, 3 columns - `display: inline-block`
- [ ] Columns - `width: 33%` ?
- [ ] Column Info - Stat number is a large font, stat text is smaller than number
- [ ] Stat text is lightgrey
- [ ] Column Info - Number and text is aligned center
- [ ] Stats Section - Bottom border - lightgrey
- [ ] container box for everything (looks to be around 90% width)
  - [ ] button with icon and text centered
  - [ ] contain with 3 links
  - [ ] evenly spaced
  - [ ] text centered
    number counter.....blacked out with my add on

### CODE REVIEW

**Comment by jorgehjr84** [comment]
https://github.com/TheIronYard--Orlando/2015--SUMMER--FEE/issues/208

**Comment by al-the-x** [comment]
Check the case on your `api/` subdirectories. Should be `api/github/users/octocat/`...

**Comment by al-the-x** [comment]
Naming files with colons in them can be confusing. If you _really_ want to organize them, use dashes (or double-dashes) in the names... or just put them in subdirectories. A flat structure is easier to look at, so nest directories judiciously.

**Comment by al-the-x** [comment]
Now that you've had some more experience planning, you're ready to take another pass at those screenshots, I'll bet.

**Comment by jorgehjr84** [comment]
Link to mobile tabs issue https://github.com/jorgehjr84/TIY-Github/issues/2

**Comment by jorgehjr84** [comment]
Link to profile details issue https://github.com/jorgehjr84/TIY-Github/issues/3

**Comment by jorgehjr84** [comment]
Link to follow bar issue https://github.com/jorgehjr84/TIY-Github/issues/4

**Pull request merged**
